### ISSUE TITLE
Database needs to be updated with changed data types.

### ISSUE THREAD

**Issue by JustBeanie** [ch0ppy35/pyTed#10]
Here's the newest dump of the db with corrected datatypes.
[newest.bak.txt](https://github.com/ch0ppy35/pyTed/files/4078832/newest.bak.txt)

**Comment by ch0ppy35** [comment]
@JustBeanie Looks good, I put in #11 .  One issue I do see, it's not creating tables in `pyted`.  It's creating them in public.  We can change this later, not a show stopper.  Works for testing right now.

**Comment by ch0ppy35** [comment]
Closing this issue
